### ISSUE TITLE
Buffer security issue

### ISSUE THREAD

**Issue by persianace** [fiefdx/node-file-encrypt#2]
Hi fiefdx
in file_encrypt.js Buffers need to be replace => Buffer() is deprecated due to security and usability issues. Should use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead
But idk which method works

**Comment by fiefdx** [comment]
@persianace Thanks for the report, the latest version fixed this.

**Comment by persianace** [comment]
Thanks for your hard work Haitao
